### ISSUE TITLE
feature request: when no hierarchy information detected hide the icon

### ISSUE THREAD

**Issue by henices** [sethyuan/logseq-plugin-hierarchy-jump#1]
![image](https://github.com/sethyuan/logseq-plugin-hierarchy-jump/assets/929715/8b597f0f-4da5-4fb6-948d-de9edf76b195)

Thanks a lot, for the amazing plugin.

**Comment by sethyuan** [comment]
I also tried to hide it when there is no hierarchy but it turns out that there is no API to unregister this button. 😅 I'll ask the Logseq's team if they can add one.

**Comment by sethyuan** [comment]
A workaround came to my mind, I think I can try it.

**Comment by henices** [comment]
when we detect  hierarchy information in the page, use css to set a color for the icon . 😃

**Comment by sethyuan** [comment]
Yes, I implemented it and published a new version.
